import unittest

from sglang.test.ascend.test_ascend_utils import E5_MISTRAL_7B_INSTRUCT_WEIGHTS_PATH
from sglang.test.ascend.test_embedding_base import BaseEmbeddingTest
from sglang.test.ci.ci_register import register_npu_ci
from sglang.test.test_utils import CustomTestCase

register_npu_ci(
    est_time=400,
    suite="full-1-npu-a3",
    nightly=True,
)


class TestE5Mistral7b(BaseEmbeddingTest, CustomTestCase):
    """Testcase: This test case verifies that the embeddings generated by the intfloat/e5-mistral-7b-instruct model in
    the SGLang framework closely match those from the Hugging Face implementation with a tolerance of 1e-5.

    [Test Category] Model
    [Test Target] intfloat/e5-mistral-7b-instruct
    """

    MODELS = [
        (E5_MISTRAL_7B_INSTRUCT_WEIGHTS_PATH, 1, 1e-5),
    ]


if __name__ == "__main__":
    unittest.main()
