name: Nightly Test For Accuracy(NPU)

on:
  # schedule:
  #   - cron: '0 2 * * *'  # Execute at 2:00 a.m. Beijing Time every day
  pull_request:
    branches:
      - main
      - testcases
    paths:
      - ".github/workflows/nightly-test-npu-accuracy.yml"
  workflow_dispatch:

concurrency:
  group: ascend-nightly-test-accuracy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-16-npu-a3:
    if: ${{ (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') }}
    runs-on: linux-aarch64-a3-16
    strategy:
      fail-fast: false
      matrix:
        part: [0]
    container:
      image: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:cann8.5.0-a3-B121'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        timeout-minutes: 240
        env:
          SGLANG_USE_MODELSCOPE: true
          SGLANG_IS_IN_CI: true
          HF_ENDPOINT: https://hf-mirror.com
        run: |
          sglang_source_path=$(pwd)
          echo "Source code path: ${sglang_source_path}"
          ln -sf ${sglang_source_path} /root/sglang

          # copy required file from our daily cache
          cp ~/.cache/modelscope/hub/datasets/otavia/ShareGPT_Vicuna_unfiltered/ShareGPT_V3_unfiltered_cleaned_split.json /tmp
          # copy download through proxy
          curl -o /tmp/test.jsonl -L https://gh-proxy.test.osinfra.cn/https://raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/test.jsonl

          # Set environment of cann
          source /usr/local/Ascend/cann/set_env.sh || true
          source /usr/local/Ascend/nnal/atb/set_env.sh || true

          sglang_pkg_path=$(pip show sglang | grep Location | awk '{print $2}')
          ascend_test_util_path=${sglang_pkg_path}/sglang/test/ascend
          mkdir -p ${ascend_test_util_path}
          mv ${ascend_test_util_path} ${ascend_test_util_path}_bak
          cp -r ${sglang_source_path}/python/sglang/test/ascend ${ascend_test_util_path}

          python3 test/registered/ascend/llm_models/test_ascend_qwen3_30b_w8a8_2p_accuracy.py
