name: Nightly Test For Accuracy(NPU)

on:
  # schedule:
  #   - cron: '0 2 * * *'  # Execute at 2:00 a.m. Beijing Time every day
  pull_request:
    branches:
      - main
      - testcases
    paths:
      - ".github/workflows/nightly-test-npu-accuracy.yml"
  workflow_dispatch:

concurrency:
  group: ascend-nightly-test-accuracy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-16-npu-a3:
    if: ${{ (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') }}
    runs-on: linux-aarch64-a3-16
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1]
    container:
      image: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:cann8.5.0-a3-B121'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        timeout-minutes: 240
        env:
          SGLANG_USE_MODELSCOPE: true
          SGLANG_IS_IN_CI: true
          HF_ENDPOINT: https://hf-mirror.com
        run: |
          python3 test/registered/ascend/llm_models/test_ascend_qwen3_235b_w8a8_8p_in2k_out2k_accuracy.py
